variables:
  REGISTRY: registry.selfdesign.org

stages:
  - prepare
  - build

prepare:
  stage: prepare
  script:
    - docker info
    #- git fetch origin
    #- git checkout edge
  
build:
  stage: build
  script:
    - IMAGE_TAG=`head -n 1 CHANGELOG.md | awk '{print $2'}`
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY
    - docker build -t $REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG --compress --squash .
    - docker tag $REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG $REGISTRY/$CI_PROJECT_PATH:latest
    - docker push $REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
    - docker push $REGISTRY/$CI_PROJECT_PATH:latest

    
